[project]
id = "mirl"
version = "0.1.0"
mach = "^6.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

# the library, and the default artifact
[artifact.libmirl]
kind = "static"
default = true
entry = "lib/libmirl.mach"
out = "lib/mirl"
targets = ["*"]
link = ["kernel32"]
need = []

[artifact.mirl]
kind = "bin"
entry = "bin/mirl.mach"
out = "bin/mirl{artifact.suffix}"
targets = ["*"]
link = ["kernel32"]
need = []

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false

[profile.debug]
default = true
opt = 0
debug = true
simd = "scalarize"
vectorize = false
float_reassoc = false

[profile.release]
opt = 2
debug = false
simd = "scalarize"
vectorize = true
float_reassoc = false

[dep.std]
git = "https://github.com/briar-systems/mach-std"
version = "^9.5.0"
