[project]
id = "mirl"
version = "0.1.0"
mach = "^6"
src = "src"
work = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-aarch64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

# the library, what a dependent's `use mirl;` binds
[artifact.mirl]
kind = "static"
default = true
export = true
entry = "lib/mirl.mach"
out = "lib/mirl"
targets = ["*"]
link = ["kernel32"]
need = []

# the command line over the library
[artifact.cli]
kind = "bin"
entry = "bin/mirl.mach"
out = "bin/mirl{artifact.suffix}"
targets = ["*"]
link = ["kernel32"]
need = []

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false

[profile.debug]
default = true
optimize = false
debug = true
simd = "scalarize"
skip = ["vectorize"]

[profile.release]
optimize = true
debug = false
simd = "scalarize"

[dep.std]
git = "https://github.com/briar-systems/mach-std"
ref = "commit/ee8f3156fb82e4150e64c17d34f8ef9df1148e8f"

[dep.mink]
git = "https://github.com/briar-systems/mink"
ref = "commit/e284774deeb29bf28a49c65d1d27d69f8367493c"
